'use strict';
(() => {
const db=window.ATLAS, cases=db.cases, byId=new Map(cases.map(c=>[c.id,c]));
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={place:'',topic:'',chapter:'',search:'',case:'',path:''};
const names={models:'Chapter 2 · Models',macro:'Chapters 6–7 · Macro overview',gdp:'Chapter 7 · GDP & CPI',inflation:'Chapters 7–8 · Inflation',unemployment:'Chapter 8 · Unemployment',tutorial:'Chapter 8 · Measurement tutorial',growth1:'Chapter 9 · Growth, Part 1',growth2:'Chapter 9 · Growth, Part 2'};
const topics=[...new Set(cases.map(c=>c.topic))].sort();
$('#topic').insertAdjacentHTML('beforeend',topics.map(t=>`<option>${esc(t)}</option>`).join(''));
$('#chapter').insertAdjacentHTML('beforeend',Object.entries(names).map(([v,t])=>`<option value="${v}">${esc(t)}</option>`).join(''));
let currentFigure=0,largeOpener=null;
function matches(c,ignorePlace=false){let q=state.search.toLowerCase().trim();return (ignorePlace||!state.place||c.places.includes(state.place))&&(!state.topic||c.topic===state.topic)&&(!state.chapter||c.chapters.includes(state.chapter))&&(!q||`${c.title} ${c.places.join(' ')} ${c.concept} ${c.story} ${c.period}`.toLowerCase().includes(q));}
function urlState(replace=false){const p=new URLSearchParams();for(const [k,v] of Object.entries(state))if(v)p.set(k,v);const h=p.toString();history[replace?'replaceState':'pushState'](null,'',location.pathname+location.search+(h?'#'+h:''));}
function readHash(){const h=location.hash.slice(1);if(h&&!h.includes('='))return;const p=new URLSearchParams(h);for(const k of Object.keys(state))state[k]=p.get(k)||'';if(!byId.has(state.case))state.case='';if(state.path&&!db.paths.some(p=>p.id===state.path))state.path='';sync();render();if(state.case)detail(false);}
function sync(){$('#search').value=state.search;$('#topic').value=state.topic;$('#chapter').value=state.chapter;}
function map(kind){const m=window.ATLAS_MAPS[kind];const content=m.features.map(f=>`<path class="land ${f.active?'active':''}" d="${f.path}" ${f.active?`data-place="${esc(f.name)}" tabindex="0" role="button" aria-label="${esc(f.name)}, ${f.count} examples" aria-pressed="false"`:''}><title>${esc(f.name)}${f.active?` · ${f.count} examples`:''}</title></path>`).join('');let labels=kind==='usa'?'<text class="map-label" x="742" y="430">GA</text><text class="map-label" x="665" y="212">MI</text><text class="map-label" x="720" y="258">OH</text>':'';
$(`#${kind}-map`).innerHTML=`<svg viewBox="${m.viewBox}" aria-label="${kind==='usa'?'United States states':'World countries'} with course examples" role="group">${content}${labels}</svg>`;}
map('usa');map('world');
const placeNames=[...new Set(cases.flatMap(c=>c.places))].sort();
function chip(p){const count=cases.filter(c=>c.places.includes(p)).length;return `<button data-place="${esc(p)}" aria-pressed="false">${esc(p)} <span aria-label="${count} examples">· ${count}</span></button>`;}
$('#us-places').innerHTML=placeNames.filter(p=>['Georgia','Michigan','Ohio'].includes(p)).map(chip).join('');
$('#world-places').innerHTML=placeNames.filter(p=>!['Georgia','Michigan','Ohio','United States (national)'].includes(p)).map(chip).join('');
function render(){const found=cases.filter(c=>matches(c));$('#result-count').textContent=`${found.length} of ${cases.length} examples`;
$('#selection').innerHTML=(state.place?esc(state.place)+' <button id="clear-place" aria-label="Clear selected place">×</button>':'All places')+(state.topic?' · '+esc(state.topic):'');
$('#case-list').innerHTML=found.map(c=>`<button class="case-button ${state.case===c.id?'active':''}" data-case="${c.id}" aria-pressed="${state.case===c.id}"><span>${esc(c.topic)} · ${c.places.length?esc(c.places[0].replace(' (national)','')):'Concept & model'}</span><strong>${esc(c.title)}</strong></button>`).join('');
$('#no-results').hidden=found.length>0;
document.querySelectorAll('[data-place]').forEach(el=>{const p=el.dataset.place,selected=state.place===p;el.setAttribute('aria-pressed',String(selected));el.classList.toggle('selected',selected);if(el.matches('path'))el.classList.toggle('dimmed',!cases.some(c=>c.places.includes(p)&&matches(c,true)));});}
function choosePlace(p){state.place=state.place===p?'':p;state.path='';urlState();render();$('#results').focus({preventScroll:true});$('#results').scrollIntoView({behavior:'auto',block:'start'});}
function showCase(id,keepPath=false){if(!byId.has(id))return;state.case=id;if(!keepPath)state.path='';urlState();render();detail(true);}
function table(data,limit=30){const rows=data.rows.slice(0,limit);return `<div class="table-wrap" tabindex="0" aria-label="Scrollable data table"><table><caption>${esc(data.label)}</caption><thead><tr>${data.columns.map(k=>`<th scope="col">${esc(k.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${data.columns.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${data.rows.length>limit?`<p class="data-notice">Showing ${limit} of ${data.rows.length} observations. The CSV contains the complete selected series.</p>`:''}<a href="${data.url}" download>Download this data · CSV</a>`;}
function figure(c){if(!c.figures.length)return '';const f=c.figures[currentFigure];return `<figure class="case-figure">${c.figures.length>1?`<div class="figure-controls" aria-label="Choose a class figure">${c.figures.map((x,i)=>`<button data-figure="${i}" class="${i===currentFigure?'chosen':''}" aria-pressed="${i===currentFigure}">${esc(x.caption)}</button>`).join('')}</div>`:''}<img src="${f.url}" alt="${esc(f.alt)}" loading="lazy"><figcaption class="figure-caption">${esc(f.caption)} · ${esc(f.credit)}</figcaption><button class="enlarge" id="enlarge-figure">Enlarge figure ↗</button></figure>`;}
function calc(c){if(c.id==='C18')return `<div class="calculator"><h3>Try the real-interest calculation</h3><label>Realized inflation: <span id="inflation-value">6</span>%<input type="range" id="inflation-input" min="0" max="12" step="0.5" value="6"></label><output id="calc-output" aria-live="polite">Approximate real rate: 2.0%</output><p>Illustrative fixed nominal interest rate: 8%. Approximation: nominal rate − realized inflation.</p></div>`;
if(c.id==='C23')return `<div class="calculator"><h3>Try the denominator</h3><label>Unemployed people, thousands<input id="u-input" type="number" min="0" max="274816" step="1" value="7003"></label><label>Labor force, thousands<input id="lf-input" type="number" min="1" max="274816" step="1" value="170723"></label><output id="calc-output" aria-live="polite">Unemployment rate: 4.10%</output><p>The initial values are the saved December 2025 data. Changed values are hypothetical. Keep unemployed people within the labor force.</p></div>`;return '';}
function detail(focus){const c=byId.get(state.case);if(!c)return;currentFigure=0;let path=db.paths.find(p=>p.id===state.path),index=path?path.cases.indexOf(c.id):-1;
const nav=path&&index>=0?`<div class="path-nav"><span>${esc(path.title)} · ${index+1}/${path.cases.length}</span><div><button data-path-step="-1" ${index===0?'disabled':''}>← Previous</button> <button data-path-step="1" ${index===path.cases.length-1?'disabled':''}>Next →</button></div></div>`:'';
$('#case-detail').innerHTML=nav+`<p class="eyebrow">${esc(c.topic)} · ${c.places.length?esc(c.places.join(' / ')):'CONCEPT & MODEL'}</p><h2 id="detail-title">${esc(c.title)}</h2><p class="detail-meta">${esc(c.period)}</p><p>${esc(c.story)}</p><div id="figure-holder">${figure(c)}</div><details><summary>${c.figures.length?'Read the graph':'Interpret the example'}</summary><p>${esc(c.read)}</p>${c.method?`<p>${esc(c.method)}</p>`:''}</details>${c.timeline.length?`<details><summary>Historical context</summary><ol class="timeline">${c.timeline.map(x=>`<li><b>${esc(x.date)}</b>${esc(x.text)}</li>`).join('')}</ol></details>`:''}<div class="takeaway"><span>CONNECT TO THE CONCEPT</span><p>${esc(c.takeaway)}</p></div>${calc(c)}
<form id="quiz" class="quiz"><p class="eyebrow">OPTIONAL · QUICK PRACTICE</p><fieldset><legend>${esc(c.quiz.question)}</legend>${c.quiz.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" required><b>${'ABCD'[i]}.</b> ${esc(o)}</label>`).join('')}</fieldset><div class="quiz-actions"><button class="primary" type="submit">Check answer</button><button type="button" id="show-answer">Show explanation</button><button type="reset" class="quiet">Try again</button></div><div id="feedback" class="feedback" role="status" aria-live="polite"></div></form>
<details><summary>Class slides & sources</summary><ul class="resource-links"><li><a href="${c.slides.url}" target="_blank" rel="noopener">${esc(c.slides.label)} ↗</a><p class="data-notice">${c.slides.references.map(r=>`${esc(names[r.deck])}, slide ${r.slide}`).join('; ')}. Completed class excerpts.</p></li>${c.sources.map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a></li>`).join('')}</ul></details>${c.data.length?`<details><summary>Explore the data · tables & downloads</summary>${c.data.map(d=>table(d)).join('')}</details>`:''}${c.further?`<details><summary>Go further · optional research</summary>${c.further.map(f=>`<p><a href="${esc(f.url)}" target="_blank" rel="noopener">${esc(f.title)} ↗</a><br>${esc(f.text)}</p>`).join('')}</details>`:''}<div class="related">${c.related.map(id=>`<button data-case="${id}">${esc(byId.get(id).title)} →</button>`).join('')}</div><p><button id="copy-link" class="quiet">Copy a link to this example</button> <button id="print-case" class="quiet">Print this example</button></p><p id="share-status" class="data-notice" role="status"></p>`;
if(focus){$('#case-detail').focus({preventScroll:true});$('#case-detail').scrollIntoView({behavior:'auto',block:'start'});}}
function answer(reveal=false){const c=byId.get(state.case),selected=$('#quiz input:checked');if(!reveal&&!selected)return;const correct=selected&&Number(selected.value)===c.quiz.answer;const box=$('#feedback');box.classList.toggle('retry',!correct&&!reveal);box.textContent=`${reveal?'Answer: '+ 'ABCD'[c.quiz.answer]+'.':correct?'Correct.':'Not quite. The correct answer is '+ 'ABCD'[c.quiz.answer]+'.'} ${c.quiz.explanation}`;}
$('#filters').addEventListener('submit',e=>e.preventDefault());
$('#filters').addEventListener('reset',()=>{state.place=state.topic=state.chapter=state.search=state.path='';setTimeout(()=>{sync();urlState();render();},0);});
$('#topic').addEventListener('change',e=>{state.topic=e.target.value;state.path='';urlState();render();});
$('#chapter').addEventListener('change',e=>{state.chapter=e.target.value;state.path='';urlState();render();});
$('#search').addEventListener('input',e=>{state.search=e.target.value;state.path='';urlState(true);render();});
document.addEventListener('click',e=>{let b=e.target.closest('[data-case],[data-place],[data-path],[data-path-step],[data-figure]');if(b){e.preventDefault();if(b.dataset.case)showCase(b.dataset.case);else if(b.dataset.place)choosePlace(b.dataset.place);else if(b.dataset.path){const p=db.paths.find(x=>x.id===b.dataset.path);state.path=p.id;state.place=state.topic=state.chapter=state.search='';sync();showCase(p.cases[0],true);}else if(b.dataset.pathStep){const p=db.paths.find(x=>x.id===state.path),ix=p.cases.indexOf(state.case)+Number(b.dataset.pathStep);if(p.cases[ix])showCase(p.cases[ix],true);}else if(b.dataset.figure){currentFigure=Number(b.dataset.figure);$('#figure-holder').innerHTML=figure(byId.get(state.case));}return;}
if(e.target.id==='clear-place'){state.place='';urlState();render();}
if(e.target.id==='show-answer')answer(true);
if(e.target.id==='enlarge-figure'){const f=byId.get(state.case).figures[currentFigure];largeOpener=e.target;$('#large-image').src=f.url;$('#large-image').alt=f.alt;$('#large-caption').textContent=f.caption;$('#image-dialog').showModal();}
if(e.target.id==='close-image')$('#image-dialog').close();
if(e.target.id==='print-case')window.print();
if(e.target.id==='copy-link'){const status=$('#share-status');if(navigator.clipboard)navigator.clipboard.writeText(location.href).then(()=>status.textContent='Link copied.').catch(()=>status.textContent='Copy the address from your browser to share this example.');else status.textContent='Copy the address from your browser to share this example.';}
});
document.addEventListener('keydown',e=>{if(e.target.matches('path[role=button]')&&['Enter',' '].includes(e.key)){e.preventDefault();choosePlace(e.target.dataset.place);}});
$('#case-detail').addEventListener('submit',e=>{e.preventDefault();answer();});$('#case-detail').addEventListener('reset',()=>{const b=$('#feedback');if(b)b.textContent='';});
$('#case-detail').addEventListener('input',e=>{if(e.target.id==='inflation-input'){const i=Number(e.target.value);$('#inflation-value').textContent=i;$('#calc-output').textContent=`Approximate real rate: ${(8-i).toFixed(1)}%`;}if(['u-input','lf-input'].includes(e.target.id)){let u=Number($('#u-input').value),lf=Number($('#lf-input').value);$('#calc-output').textContent=($('#u-input').value===''||$('#lf-input').value===''||!Number.isFinite(u)||!Number.isFinite(lf)||lf<=0||u<0||u>lf||lf>274816)?'Use valid counts: 0 ≤ unemployed ≤ labor force ≤ 274,816.':`Unemployment rate: ${(100*u/lf).toFixed(2)}% (hypothetical if changed)`;}});
$('#image-dialog').addEventListener('close',()=>{if(largeOpener?.isConnected)largeOpener.focus();});
$('#zoom-europe').addEventListener('click',e=>{const z=e.target.getAttribute('aria-pressed')!=='true';e.target.setAttribute('aria-pressed',String(z));e.target.textContent=z?'Show whole world':'Zoom to Europe';$('#world-map svg').setAttribute('viewBox',z?'445 65 170 105':window.ATLAS_MAPS.world.viewBox);});
$('#path-list').innerHTML=db.paths.map(p=>`<article class="path-card"><p class="eyebrow">${p.cases.length} CASES · ${p.minutes}</p><h3>${esc(p.title)}</h3><p>${p.cases.map(id=>esc(byId.get(id).title)).join(' → ')}</p><button data-path="${p.id}">Start this path →</button></article>`).join('');
$('#concept-list').innerHTML=cases.filter(c=>!c.places.length).map(c=>`<button data-case="${c.id}">${esc(c.title)} →</button>`).join('');
// Curated comparisons keep their own units and definitions.
function comparison(reset=true){const mode=$('#comparison').value,select=$('#compare-place');if(reset){const list=mode==='youth'?['Georgia','Michigan','Ohio','Spain','France','Germany']:mode==='benefits'?['United States','Germany','Spain','France']:[];select.innerHTML=list.map(n=>`<option>${esc(n)}</option>`).join('');}$('#compare-place-label').hidden=mode==='ageing';const place=select.value;let html='';
function bar(label,value,max,gold=false){return `<div class="stat-row"><div class="stat-label"><span>${esc(label)}</span><strong>${Number(value).toFixed(1)}%</strong></div><div class="bar-track"><div class="bar-value ${gold?'gold':''}" style="width:${Math.max(0,Math.min(100,100*Number(value)/max))}%"></div></div></div>`;}
if(mode==='youth'){const data=byId.get('C22').data[0].rows;const group=p=>{const rows=data.filter(r=>r.place===p);return `<div class="compare-box"><h3>${esc(p)}</h3>${rows.map((r,i)=>bar('Ages '+r.age,r.rate,25,i===1)).join('')}<p class="data-notice">2024 · percent of each age group’s labor force. Common bar scale: 0–25%.${rows[0].lower?' State 90% confidence intervals remain in the source figure.':''}</p></div>`;};const other=place==='Spain'?'Georgia':'Spain';html=`<div class="compare-grid">${group(place)}${group(other)}</div><p class="data-notice">Countries and states differ in geographic scale. This descriptive comparison does not identify a policy effect. <button data-case="C22">Open the full graph and uncertainty intervals →</button></p>`;}
if(mode==='benefits'){const rows=byId.get('C20').data[0].rows;const group=p=>{const r=rows.find(x=>x.country===p);return `<div class="compare-box"><h3>${esc(p)}</h3>${bar('Month 2',r.month2,100)}${bar('Month 24',r.month24,100,true)}<p class="data-notice">Policy year ${r.policy_year}. Common scale: 0–100% of modeled net income in work.</p></div>`;};html=`<div class="compare-grid">${group(place)}${group(place==='United States'?'Germany':'United States')}</div><p class="data-notice">Qualifying single adult, age 40, without children, formerly earning the average wage; housing support included. Not average payments to all unemployed people. <button data-case="C20">Open assumptions and sources →</button></p>`;}
if(mode==='ageing'){const c=byId.get('C24');html=`<div class="compare-grid">${c.figures.map(f=>`<div class="compare-box"><h3>${esc(f.caption)}</h3><a href="${f.url}" target="_blank" rel="noopener"><img src="${f.url}" alt="${esc(f.alt)}"></a></div>`).join('')}</div><p class="data-notice">Population is a total percent change; GDP per person is annual growth. Periods differ. The projected panel is conditional on OECD productivity and employment assumptions. <button data-case="C24">Read the assumptions and data →</button></p>`;}
$('#compare-content').innerHTML=html;}
$('#comparison').addEventListener('change',()=>comparison());$('#compare-place').addEventListener('change',()=>comparison(false));comparison();
window.addEventListener('popstate',readHash);window.addEventListener('hashchange',readHash);readHash();
})();
